import type { Metadata } from 'next';
import { Inter, Raleway, Montserrat } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/cores/Header';
import { Footer } from '@/components/cores/Footer';
import TanstackProvider from '@/providers/TanstackProvider';
import { usePathname } from 'next/navigation';
import { Suspense } from 'react';
import Loading from './loading';
const raleway = Raleway({ subsets: ['latin'] });
const montserrat = Montserrat({ subsets: ['latin'] });
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <TanstackProvider>
        <head>
          <script
            defer
            src={`https://maps.googleapis.com/maps/api/js?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&libraries=places`}
            async
          ></script>
        </head>
        <body className={`${raleway.className}`}>
          <Header />
          <Suspense fallback={<Loading />}>
            <div className="min-h-screen">{children}</div>
          </Suspense>
          <Footer />
        </body>
      </TanstackProvider>
    </html>
  );
}
