import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/cores/Header';
import { Footer } from '@/components/cores/Footer';
import { Toaster } from '@/components/ui/toaster';
import TanstackProvider from '@/providers/TanstackProvider';
import ReduxProvider from '@/providers/ReduxProvider';
import ProtectedRoute from '@/components/ProtectedRoute';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <TanstackProvider>
            <ProtectedRoute>
              <Header />
              <div className="">
                {children}
                <Toaster />
              </div>
              <Footer />
            </ProtectedRoute>
          </TanstackProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
